# file: roles/common/tasks/main.yml
- name: Install required base packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - git
    - zip
    - unzip

- name: Install python-software-properties
  apt: name=python-software-properties state=present
