---
- hosts: all
  become: true
  vars:
    document_root: /vagrant   # variable defined directly in the playbook
    www_user: vagrant         # another variable defined directly in the playbook
    www_group: vagrant
  vars_files:
    - /vars/external_vars.yml # for storing sensitive info out of version control
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
  roles:
    - common
    - nginx
    - mysql
    - php
    - php-devtools
    - php-fpm
    - laravel-quickstart
